//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cocktail
    {
        public int idCocktail { get; set; }
        public string nombre { get; set; }
        public int precio_v { get; set; }
        public int? ing1 { get; set; }
        public int? ing2 { get; set; }
        public int? ing3 { get; set; }
        public int? ing4 { get; set; }
        public int? ing5 { get; set; }
        public string descripcion { get; set; }
    }
}
