//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int idDetalle { get; set; }
        public int? idPedido { get; set; }
        public string nombreConsumo { get; set; }
        public string estado { get; set; }
        public int? costo { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
