//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        public int idInsumo { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public int precio_v { get; set; }
        public int precio_c { get; set; }
        public int stock { get; set; }
        public int stock_min { get; set; }
        public int porcion { get; set; }
    }
}
